dist: trusty
sudo: required
language: generic

services:
  - docker

env:
  global:
  - NJOBS="2"
  matrix:
  - COQ_IMAGE="coqorg/coq:8.4"
  - COQ_IMAGE="coqorg/coq:8.5"
  - COQ_IMAGE="coqorg/coq:8.6"
  - COQ_IMAGE="coqorg/coq:8.7"
  - COQ_IMAGE="coqorg/coq:8.8"
  - COQ_IMAGE="coqorg/coq:dev"

install: |
  # Prepare the COQ container
  docker run -d -i --init --name=COQ -v ${TRAVIS_BUILD_DIR}:/home/coq/demo -w /home/coq/demo ${COQ_IMAGE}
  docker exec COQ /bin/bash --login -c "
    # This bash script is double-quoted to interpolate Travis CI env vars:
    echo \"Build triggered by ${TRAVIS_EVENT_TYPE}\"
    export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '
    set -ex  # -e = exit on failure; -x = trace for debug
    opam update -y -u
    opam install -y -v -j ${NJOBS} coq-mathcomp-ssreflect
    "

script:
- echo -e "${ANSI_YELLOW}Building Demo...${ANSI_RESET}" && echo -en 'travis_fold:start:testbuild\\r'
- |
  docker exec COQ /bin/bash --login -c "
    export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '
    set -ex
    sudo chown -R coq:coq /home/coq/demo
    coq_makefile -f _CoqProject -o Makefile
    make
    "
- docker stop COQ  # optional
- echo -en 'travis_fold:end:testbuild\\r'
